apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-app-img
  name: springboot-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: docker-app-img
  template:
    metadata:
      labels:
        app: docker-app-img
    spec:
      containers:
      - name: docker-app-img
        image: 725006688946.dkr.ecr.ap-south-1.amazonaws.com/docker-app-img:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-app-img
    k8s-app: docker-app-img
  name: springboot-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: docker-app-img
